#!/bin/bash
set -eu -o pipefail
safe_source () { [[ ! -z ${1:-} ]] && source $1; _dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; _sdir=$(dirname "$(readlink -f "$0")"); }; safe_source
# end of bash boilerplate

safe_source $_sdir/../lib/all.sh

[[ -f ${1:-} ]] || die "First argument should be initrd file"
initrd_file=$(readlink -f ${1:-})

[[ $(whoami) = "root" ]] || { sudo $0 "$@"; exit 0; }

unpack_folder=$_sdir/initrd.d
unpack_meta=$_sdir/initrd.meta

if [[ -d $unpack_folder ]] && prompt_yes_no "delete contents of $unpack_folder ?"; then
    rm -rf $unpack_folder
fi 

mkdir -p $unpack_folder

cd $unpack_folder
file $initrd_file
gunzip < $initrd_file | cpio -i --make-directories
cd $_sdir
echo "$(basename $initrd_file)" > $unpack_meta

