#!/bin/busybox-static sh

# Copyright 2015 Sergey Kvachonok
# Licensed under the CC-BY-SA-3.0 license.
# Based in part on https://wiki.gentoo.org/wiki/Custom_Initramfs
# which is:
#     Copyright 2001–2015 Gentoo Foundation, Inc.
#     Licensed under the CC-BY-SA-3.0 license.

# Install the symlinks to all busybox applets first.
/bin/busybox-static mkdir -p /usr/sbin /usr/bin /sbin
/bin/busybox-static --install -s

rescue_shell() {
    echo "Something went wrong. Dropping to a shell."
    exec sh
}

cmdline() {
    local value
    value=" $(cat /proc/cmdline) "
    value="${value##* $1=}"
    value="${value%% *}"
    [ "$value" != "" ] && echo "$value"
}

# Mount the /dev, /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "Waiting for devices..."
sleep 2

echo "Registering BTRFS block devices"
echo "Root partition candidates:" /dev/sd[a-f]2
btrfs-register /dev/sd[a-f]2

# Mount the root filesystem.
mount -t btrfs -o ro $(findfs $(cmdline root)) /mnt/root || rescue_shell

# Clean up.
umount /proc
umount /sys
umount /dev

# Remount /dev.
mount -t devtmpfs none /mnt/root/dev

# Boot the real thing.
exec switch_root /mnt/root /sbin/init